LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE    := mnvmcore
LOCAL_SRC_FILES := ADBEMDEV.c ASCEMDEV.c GLOBGLUE.c IWMEMDEV.c M68KITAB.c MINEM68K.c MOUSEMDV.c ROMEMDEV.c RTCEMDEV.c SCCEMDEV.c SCRNEMDV.c SCSIEMDV.c SONYEMDV.c VIA2EMDV.c VIAEMDEV.c VIDEMDEV.c PROGMAIN.c JNIGLUE.c

include $(BUILD_SHARED_LIBRARY)
