LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE    := mnvmcore
LOCAL_SRC_FILES := GLOBGLUE.c IWMEMDEV.c KBRDEMDV.c M68KITAB.c MINEM68K.c MOUSEMDV.c ROMEMDEV.c RTCEMDEV.c SCCEMDEV.c SCRNEMDV.c SCSIEMDV.c SNDEMDEV.c SONYEMDV.c VIAEMDEV.c PROGMAIN.c JNIGLUE.c

include $(BUILD_SHARED_LIBRARY)
