/*
	Configuration options used by platform specific code.

	This file is automatically generated by the build system,
	which tries to know what options are valid in what
	combinations. Avoid changing this file manually unless
	you know what you're doing.
*/

#define RomFileName "MacII.ROM"
#define EnableDragDrop 0
#define EnableAltKeysMode 0
#define SwapCommandControl 0
#define EnableMagnify 0
#define VarFullScreen 0
#define WantInitFullScreen 0
#define MayFullScreen 1
#define MayNotFullScreen 1
#define WantInitMagnify 0
#define WantInitRunInBackground 0
#define WantInitNotAutoSlow 1
#define NeedRequestInsertDisk 1
#define NeedDoMoreCommandsMsg 1
#define NeedDoAboutMsg 1
#define UseControlKeys 1
#define UseActvCode 0

/* version and other info to display to user */

#define NeedIntlChars 0
#define kStrAppName "Mini vMac"
#define kAppVariationStr "minivmac-3.2.3-android (Mac II)"
#define kStrCopyrightYear "2012"
#define kMaintainerName "Gil Osher"
#define kStrHomePage "http://gil.theoshers.com/"
