/*
	see comment in OSGCOMUI.h

	This file is automatically generated by the build system,
	which tries to know what options are valid in what
	combinations. Avoid changing this file manually unless
	you know what you're doing.
*/
#include <jni.h>

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <sys/time.h>
#include <sys/times.h>
#include <fcntl.h>
#include <sys/stat.h>
#include <errno.h>
#include <unistd.h>
#include <dlfcn.h>

#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>

#include <assert.h>
#include <stdarg.h>
#include <ctype.h>
#include <signal.h>

#include <android/log.h>

#define CanGetAppPath 0
#define HaveAppPathLink 1
#define TheAppPathLink "/proc/self/exe"
#define HaveSysctlPath 0

#define EnableDragDrop 0
#define WantOSGLUJNI 1

#define kStrAppName "Mini vMac"
#define kAppVariationStr "minivmac-37.03-lx64"
#define kStrCopyrightYear "2020"
#define kMaintainerName "Gil Osher"
#define kStrHomePage "https://miniv.gil.ninja"
